# -*- coding: utf-8 -*-
"""Privacy amplification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x03wuK4Oj5yUh3y0gwcsOAl-Ppaq1Vlf
"""

# Function to hash the key for privacy amplification
def hash_key(key):
    key_str = ''.join(map(str, key))
    hashed_key = sha256(key_str.encode()).hexdigest()
    return hashed_key